language: node_js
sudo: false
node_js:
- '10'
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: Y3XqOlkC8YHa5W0HWw78Ky8uxNw0o7AVX7M1pnKoT96TEkWhxgDr7Ii8Im/SElo8KVG17QRdmYAUamR9DN28FqIxIha9cPEu/1QZagsSBMM1Lyavak8xKmZVW3kBHRVl2/7kyXVXc2fRElT5jQdDifcWxIjo0bRGU4KkpHf0gArMqEMOyqcVQoGWFLbeatONHOJad/xbYz1iugaXaY0mU2l2cCBABpsH3ee/mdsYsTqTp21VtgnQPuDSM7SaywXGSgbO3F/tJQVPyWO4iLhGoSEBlfxewtQC1W6kNAE60JAvhUvE+Ssr/wW1iFpQw/IeW83eckoH1NEH4cdA6q+1Ao37gfr9DqdMzDxbrEZygvbUp9RNjChmResGJSg5/WMDuVlhpqLqmvYXzN7xsi5mCj9JPQnFIj2B8pTtD97yRNZovp71HK3ubrEhQd9YdP2IXCiC+xP/oTvsuR21DewCbblxbH9Nc+WbBHzlALX+u06g0P6pofV6525O+kBbLUBusYb2CRnwkH5nNCbBLteAHphVwjBhlDBFhpkrvuGH0uvDI71ISEL9RBR0rfwiVphDrtsERKMWE7G+xhxckatSe952EAy8TwQRvu//A+bJ2TO8OSUSogcjhO1u4dh2viXJmwi0idRa3w+MSOYNNe1VoI2/F/foWnrot7wrZYbNcjk=
